services:
  qdrant:
    image: qdrant/qdrant:latest
    env_file:
      - src/config/.env
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant/storage